[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pcal"
version = "0.1.2"
description = "Persian calendar CLI"
requires-python = ">=3.10"
dependencies = [
    "rich",
    "jdatetime",
]

[project.scripts]
pcal = "pcal.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
